# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema:
      - ./src/lib/graphql/schema.json # or https://countries.trevorblades.com/graphql
    documents:
      - '**/*.gql'
    extensions:
      endpoints:
        default:
          url: https://countries.trevorblades.com/graphql
      codegen:
        generates:
          ./src/lib/graphql/$kitql/graphqlTypes.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
              - typescript-document-nodes

          ./src/lib/graphql/$kitql/graphqlStores.ts:
            plugins:
              - '@kitql/graphql-codegen'
            config:
              importBaseTypesFrom: $lib/graphql/$kitql/graphqlTypes

          # # Almost ready for REPL.
          # # Just need to remove: TypedDocumentNode
          # ./src/lib/graphql/$kitql/graphqlStores.js.ts:
          #   plugins:
          #     - typed-document-node
          #     - '@kitql/graphql-codegen'
          #   config:
          #     jsDocStyle: true
          #     clientPath: './kitQLClient'

        config:
          useTypeImports: true
